### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by kaiiwoo** [kaiiwoo/lseg_ws#1]
- [x] Flaot2Darray에 2D Tensor 담아서 publish 시 컴퓨터 터지는 현상 해결 -> RAM / Swap 메모리 이슈 인듯
- [x] GPU로 돌릴 시 input / network device mismatch 이슈
- [x] 임의의 text subscribe해서 text feature도 제대로 나오는지 확인
- [x] image feature (not pixel)도 제대로 나오는지 확인
